//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_ride
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRegister
    {
        public int CarId { get; set; }
        public string CarNum { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Available { get; set; }
    }
}
