//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_ride
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
       // [RemoteAttribute("IsUserExsists", "Tablename",ErrorMessage = "User already exists### Choose some other name.")]
        public string CustomerAddress { get; set; }
      //  [Required(ErrorMessage = "You must provide a phone number")]
       // [Display(Name = "Home Phone")]
        //[DataType(DataType.PhoneNumber)]
       // [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")] public string PhoneNumber { get; set; }

        public Nullable<int> Mobilenumber { get; set; }
        
        public Nullable<int> LicenceNumber { get; set; }
    }
}
