//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_ride
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Register
    {
        [Required]
        public string UserID { get; set; }
        [Required]

        [RemoteAttribute("IsUserExsists", "Customer", ErrorMessage = "User Name exist.... Choose some other name.")]

        public string Username { get; set; }
        [Required]


        public string Userpassword { get; set; }
        [DataType(DataType.Password)]
       

        public string role { get; set; }
        

    }
}
